notifications:
  email: false

sudo: false
language: python
python: 3.4
cache: pip

env:
  global:
    - STACK_NAME=bridgepf-$TRAVIS_BRANCH
    - DNS_HOSTNAME=$STACK_NAME
    - DNS_DOMAIN=sagebridge.org

before_install:
  - mkdir ~/.aws
  - echo -e "[default]\nregion=us-east-1" >> ~/.aws/config
  - echo -e "[default]\naws_access_key_id=$AwsKey\naws_secret_access_key=$AwsSecretKey" >> ~/.aws/credentials

install:
  - pip install --upgrade awscli

script:
  - ./deploy_infra.sh
